export const __curry_param__ = Symbol.for('design:curry_param')
export const __message__ = Symbol.for('__message__')
export const __type_guard__ = Symbol.for('__type_guard__')
export const __message_formator__ = Symbol.for('__message_formator__')
export const __validator_message__ = Symbol.for('__validator_message__')
export const __validator_message_formator__ = Symbol.for('__validator_message_formator__')
